7-swap
sgmakgg/PSHW pull request #3
Opened 2024-01-17 16:45 UTC by sgmakgg

2024-01-20 12:39 UTC, Levitinn requested changes

2024-01-20 12:39 UTC, Levitinn commented on 7-swap/7-swap.ts
> +const obj: Record<string, number> ={
создай отдельный тип и указывай его при типизации. сейчас ты трижды указываешь один и тот же тип 
 Record<number, string>, а если положить его в переменную, то это будет гораздо легче читать

2024-01-20 14:26 UTC, sgmakgg commented on 7-swap/7-swap.ts
> +const obj: Record<string, number> ={
Поправил

2024-01-22 17:17 UTC, Levitinn approved these changes

2024-01-22 18:03 UTC, merged