sortby
sgmakgg/PSHW pull request #5
Opened 2024-01-30 18:05 UTC by sgmakgg

2024-01-31 15:25 UTC, Levitinn requested changes

2024-01-31 15:25 UTC, Levitinn commented on 11-sort-by/sortapp.ts
> +let users: any[];
почему тип - any[]?

2024-01-31 18:52 UTC, sgmakgg commented on 11-sort-by/sortapp.ts
> +let users: any[];
fixed

2024-01-31 18:55 UTC, Levitinn approved these changes

2024-02-01 11:05 UTC, sgmakgg commented on 11-sort-by/sortapp.ts
> +let users: IUser[];
Точно

2024-02-01 11:06 UTC, merged